version: 2.1

jobs:
  check:
    docker:
      - image: gradle:8.12-jdk21

    steps:
      - run:
          name: "check"
          command: "gradle check"

workflows:
  say-hello-workflow:
    jobs:
      - check
