version: 2.1

jobs:
  check:
    docker:
      - image: cimg/openjdk:17.0

    steps:
      - run:
          name: "check"
          command: "./gradlew check"

workflows:
  say-hello-workflow:
    jobs:
      - check
